sudo: true
dist: trusty
language: c
compiler: gcc
matrix:
  include:
  - env: PG=9.3
  - env: PG=9.4
  - env: PG=9.5
  - env: PG=9.6
  - env: PG=10
  - env: PG=11
before_install:
  - sudo pg_dropcluster --stop 9.2 main
  - sudo service postgresql stop
  - sudo sed -ri 's/#(create_main_cluster) .*$/\1 = false/' /etc/postgresql-common/createcluster.conf
  - if ! sudo -E apt-get -yq --no-install-suggests --no-install-recommends $(travis_apt_get_options) install postgresql-$PG postgresql-server-dev-$PG; then echo; fi
  - sudo pip install --upgrade cpp-coveralls
script:
  - |
    set -e
    export PATH=/usr/lib/postgresql/$PG/bin:$PATH
    sudo make USE_PGXS=1 ENABLE_GCOV=1 install
    bash -x test.sh
after_success:
    - gcov --version
    - coveralls --gcov-options '\-lr'
